###############################################################
#  Generated by:      Cadence Encounter 13.27-s024_1
#  OS:                Linux x86_64(Host ID ssh7.eecs.wsu.edu)
#  Generated on:      Mon Apr 23 15:09:32 2018
#  Design:            myPMul32_4
#  Command:           saveDesign fill.enc
###############################################################
current_design myPMul32_4
create_clock [get_ports {g_inClk}]  -name myCLK -period 6.400000 -waveform {0.000000 3.200000}
set_propagated_clock  [get_ports {g_inClk}]
